# Generated by Django 4.1.7 on 2023-03-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=200)),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=200)),
                ('ticket_body', models.TextField()),
                ('request_name', models.CharField(max_length=200)),
                ('request_subject', models.CharField(max_length=200)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itsuppoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.itteam')),
                ('ticketNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tickets')),
            ],
        ),
        migrations.AddField(
            model_name='itteam',
            name='ticketNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tickets'),
        ),
    ]
